# Generated by Django 3.2.4 on 2021-08-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210823_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Sighting Date'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='notes',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time_of_day',
            field=models.CharField(choices=[('A', 'Dawn'), ('B', 'Morning'), ('C', 'Midday'), ('D', 'Afternoon'), ('E', 'Dusk'), ('F', 'Evening'), ('G', 'Midnight')], default='A', max_length=1, verbose_name='Time of Day'),
        ),
    ]
