# Generated by Django 3.2.4 on 2021-08-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210823_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='notes',
            field=models.TextField(max_length=150),
        ),
    ]
