# Generated by Django 3.2.4 on 2021-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210824_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptid',
            name='evidence',
            field=models.ManyToManyField(to='main_app.Evidence'),
        ),
    ]
