# Generated by Django 3.2.4 on 2021-08-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptid',
            options={'ordering': ['name']},
        ),
    ]
